### ISSUE TITLE
Not compiling on Linux

### ISSUE THREAD

**Issue by edubart** [mackron/minifs#1]
I got the following errors while trying `minifs` on linux:

```
./minifs.h:230:42: warning: ‘struct stat64’ declared inside parameter list will not be visible outside of this definition or declaration
  230 | mfs_result mfs_fstat(FILE* pFile, struct stat64* info);
      |                                          ^~~~~~
In file included from /home/bart/projects/nelua/nelua-lang/nelua_cache/minifs-test.c:29:
./minifs.h:1611:42: warning: ‘struct stat64’ declared inside parameter list will not be visible outside of this definition or declaration
 1611 | mfs_result mfs_fstat(FILE* pFile, struct stat64* info);
      |                                          ^~~~~~
./minifs.h:1611:12: error: conflicting types for ‘mfs_fstat’
 1611 | mfs_result mfs_fstat(FILE* pFile, struct stat64* info);
      |            ^~~~~~~~~
In file included from /home/bart/projects/nelua/nelua-lang/nelua_cache/minifs-test.c:29:
./minifs.h:230:12: note: previous declaration of ‘mfs_fstat’ was here
  230 | mfs_result mfs_fstat(FILE* pFile, struct stat64* info);
      |            ^~~~~~~~~
In file included from /home/bart/projects/nelua/nelua-lang/nelua_cache/minifs-test.c:29:
./minifs.h:1613:1: error: expected identifier or ‘(’ before ‘{’ token
 1613 | {
      | ^
./minifs.h: In function ‘mfs_copy_file__posix’:
./minifs.h:2110:1: warning: control reaches end of non-void function [-Wreturn-type]
 2110 | }
      | ^
```

### Issues I could spot
- There is an extra `;` on this line https://github.com/mackron/minifs/blob/master/minifs.h#L1611.
- stat function and struct is not defined early in the implementation, it's missing the `<sys/stat.h>` include on the file beginning.
- Both `stat64` and `fstat64` are not defined unless I manually define `_LARGEFILE64_SOURCE` before including `minifs.h`
- A return is missing in `mfs_copy_file__posix`

### Discussion
I've noticed that some other libraries uses the original `fstat` function instead of `fstat64` on POSIX systems, usually by defining this before including headers:
```
#define _LARGEFILE_SOURCE       1
#define _FILE_OFFSET_BITS       64
```
Maybe this way it would be more portable, and less problematic, also this enables large files for all APIs (`ftell`, `fseek`, `stat`). But if sticking with 64 suffix, from what I've read this requires `_LARGEFILE64_SOURCE` always defined.

**Comment by mackron** [comment]
I've merged your pull requests. Thanks!
